### ISSUE TITLE
Filling path to data manually in CrystFEL GUI

### ISSUE THREAD

**Issue by XrayViz** [taw10/crystfel#1]
It would be great if one can fill the path to data by copy-paste instead of navigating through folders.

**Comment by taw10** [comment]
I'm improving the data import right now, but there is actually already a way to do what you want - it's just not very discoverable:
Open the data import file chooser as usual, then simply type "/".  The navigation buttons at the top of the chooser window should be replaced by an entry widget.  You can even paste directly with Ctrl+V (or applicable paste shortcut), without typing "/".
Hope that helps!
