### ISSUE TITLE
Group definitions must come after panel definitions

### ISSUE THREAD

**Issue by biochem-fan** [taw10/crystfel#10]
If groups are defined before its panels are defined, we get this error:

```
Unknown panel group 'q1'
Unknown panel group 'q2'
...
Invalid top-level line 'group_all'
```

Rigid body definitions did not have this order requirement.

Is this by design? If so, it would be nice to document this.

**Comment by biochem-fan** [comment]
One more documentation suggestion:

> All corrections must sum to zero at each level of hierarchy

This reasonable constraint would be worth documenting.

**Comment by taw10** [comment]
Ok, I've added a note to the manual page and also extended the error message to suggest moving the hierarchy definitions.

About the constraint:
>> All corrections must sum to zero at each level of hierarchy

>This reasonable constraint would be worth documenting.

I'm not so sure.  I think it would be confusing to mention, except perhaps in the upcoming paper where the whole algorithm is explained in detail.  The reason for this constraint is to avoid a duplicated degree of freedom, e.g. it must move the overall beam center by moving the detector at the top level, not by moving all four quadrants in the same direction.  There's no "constraint" as such, but if we allow both degrees of freedom then we get a singular matrix and the algorithm breaks.

**Comment by biochem-fan** [comment]
>  The reason for this constraint is to avoid a duplicated degree of freedom, e.g. it must move the overall beam center by moving the detector at the top level, not by moving all four quadrants in the same direction. There's no "constraint" as such, but if we allow both degrees of freedom then we get a singular matrix and the algorithm breaks.

Exactly. I knew this redundant degree of freedom, so I was worried when I saw both level 0 translation and level 1 translations were simultaneously refined with `-l1`. By looking at the source code, I learnt this redundancy was removed by constraining the sum of the level 1 translations to be zero and was relieved. If this had been documented, I would not have worried and had to read the source code myself. So at least for me, mentioning this would be assuring, not confusing.
