### ISSUE TITLE
align_detector corrupts bad region definitions

### ISSUE THREAD

**Issue by biochem-fan** [taw10/crystfel#11]
In our SACLA MPCCD geometry file, we have this for the second panel (q2):

```
data = /%/data

q2/adu_per_eV = 0.000999
q2/min_fs = 0
q2/min_ss = 1024
q2/max_fs = 511
q2/max_ss = 2047
q2/fs = 0.006215x -0.999981y
q2/ss = 0.999981x +0.006215y
q2/corner_x = 36.444600
q2/corner_y = 497.856016

badq2l1/min_fs = 0
badq2l1/max_fs = 4
badq2l1/min_ss = 1024
badq2l1/max_ss = 2047
badq2l1/panel  = q2
```

Note that eight 512 x 1024 px panels are stacked along the slow (1024 px) axis into a HDF5 dataset.

`align_detector` rewrites this bad region definition as follows:

```
bad_badq2l1/panel = q2
bad_badq2l1/min_fs = 0
bad_badq2l1/max_fs = 4
bad_badq2l1/min_ss = 0
bad_badq2l1/max_ss = 1023
```

It seems that `min_ss` and `max_ss` have been rewritten in terms of the panel's **local** data coordinate.

However, `indexamajig` still interprets them in terms of the **global** data coordinate system.

```
Bad region 'bad_badq2l1' is outside the panel bounds (q2) as presented in data (0 1024, 511 2047 inclusive): Bad region 0,0 to 4, 1023 inclusive
```

I don't know which is intended. Earlier versions worked in the same way as `indexamajig`, which I prefer.

**Comment by taw10** [comment]
Thanks for reporting again.  This should be fixed now, and I've also added a test to the suite (dc02fa26c21346ab4b1d6588fa32c307553a6949) to make sure it doesn't come back.
